# Generated by Django 5.1.3 on 2024-12-03 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruit_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_components',
            name='message',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
