# Generated by Django 5.1.2 on 2024-12-03 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fruit_app', '0003_category_customer_remove_cart_components_message_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart_components',
        ),
    ]
