# Generated by Django 5.1.2 on 2024-12-03 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruit_app', '0004_delete_cart_components'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart_components',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('product_img', models.ImageField(upload_to='media/cart')),
                ('address', models.CharField(max_length=100)),
                ('town', models.CharField(max_length=50)),
                ('phone_num', models.CharField(max_length=15)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('message', models.CharField(max_length=250)),
            ],
        ),
    ]
