# Generated by Django 5.1.2 on 2024-12-03 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruit_app', '0005_cart_components'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_fruit',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='uploads/product/'),
        ),
    ]
