# Generated by Django 5.1.2 on 2024-12-03 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruit_app', '0006_product_is_fruit_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_fruit',
            field=models.BooleanField(default=False),
        ),
    ]
