# Generated by Django 5.1.3 on 2024-12-03 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fruit_app', '0007_alter_product_is_fruit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_fruit',
        ),
    ]
