# Generated by Django 5.1.3 on 2024-12-03 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruit_app', '0008_remove_product_is_fruit'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_fruit',
            field=models.BooleanField(default=False),
        ),
    ]
