# Generated by Django 5.1.3 on 2024-12-04 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruit_app', '0009_product_is_fruit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart_components',
            name='email',
        ),
        migrations.AddField(
            model_name='cart_components',
            name='product_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, default='', max_length=2000, null=True),
        ),
    ]
