# Generated by Django 5.1.3 on 2024-12-08 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fruit_app', '0011_cart_components_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart_components',
            name='user',
        ),
    ]
